version: "3.8"

services:
  minio-setup:
    restart: on-failure
    image: minio/mc
    depends_on:
      - minio
      - backend
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set server http://minio:9000 minio minio123 && \
      /usr/bin/mc mb --ignore-existing server/test-bucket && \
      /usr/bin/mc admin config set server notify_webhook:1 queue_limit="10000" endpoint="http://backend:80/events" queue_dir="/tmp/minio-queue" auth_token=token && \
      /usr/bin/mc admin service restart server && \
      /usr/bin/mc event add server/test-bucket arn:minio:sqs::1:webhook --event put && \
      /usr/bin/mc cp /data/minio.png server/test-bucket/minio.png;
      "
    volumes:
      - ./images:/data:ro
      - ./policy.json:/tmp/policy.json:ro

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    image: ealen/echo-server

